"""initial migration

Revision ID: 06b9916351b3
Revises: 
Create Date: 2023-02-26 10:44:12.120446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b9916351b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_parent'), 'node', ['parent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_parent'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
