"""contraints changing

Revision ID: 3f5d6ebc0ae4
Revises: 0d78ff19502c
Create Date: 2023-02-26 18:27:55.135735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5d6ebc0ae4'
down_revision = '0d78ff19502c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'parent',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'parent',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
